# -*- coding: utf-8 -*-
"""DataStructueAndAlgorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Hqx92wI5nMRJm37mjo7SLHabssVDEF2
"""

a= 10
b= 10
a+b